---
title: "Hotspots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(foreign)
```


```{r deep_dive_v1 file, include=FALSE}
library(haven)
deep_dive_1 <- read_csv("/Users/mialeung/Google Drive/AVR/data/deepdive_v1.csv") 
View(deep_dive_1)
geo_hotspots<- group_by(deep_dive_1, geoid) %>% summarise(omv_p= mean(omv_p))%>% arrange(desc(omv_p))
top_100<-head(geo_hotspots,100)

top_100_info<- inner_join(top_100, deep_dive_1) 
#top_100_info_mod <- is.numeric(top_100, geoid) 
  #tried the above line, it didn't work for is.numeric or as.numeric
top_100_info_mod <- as.numeric(top_100, geoid)
geom_point(top_100_info, aes(x=geoid, y=omv_p))
#error msg that geoid doen't exist, but it should as glimpse of top_100 shows it as a chr and I tried to convert it to a num for geom_point viz. same with omv_p. 

geom_point(top_100_info, aes(x=z_rural_urban, y=omv_p))
#same error message when I try to use z_rural_urban variable which glimpse also coubts as dbl

geom_point(top_100_info, aes(x=zregndate, y=age))
#again, same error message. both x & y are int type so it *must* be the dataset that is causing the issues here. 

```


Possible hotspot evaluation criteria (external):
-Average rent (and if it has changed recently)
-Major employers
-Housing types (condo, co-op, houses)
-Ownership vs Rental
-If children reside in the area 
-Previous use of the land 
-Proximity to farming
