file---
title: "Long Run Voter Patterns"
output: html_document
---
## Question
What is the long-run pattern of voter registration in Oregon? How has this changed with the start of AVR?
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(foreign)
library(readxl)
library(lubridate)
```


```{r import, include=TRUE}
setwd("~/Google Drive/Research/AVR/data/Monthly_Voter_Registration Reports/xlsx_Versions_by_Year/")

# First get a vector list of the file names we want to process

file_names <- list.files(pattern = "*.xlsx", include.dirs = TRUE, full.names = TRUE,
                        recursive = TRUE)

# However, the files that are stored in the "2012" directory are not in a compatible
# format, so we need to remove these from the vector

# NOTE if you receive an error that a file cannot be opened with a pattern
# "./YYYY/~..." this is because you have Excel open. Close Excel.

file_names2 <- file_names[(substr(file_names,3,6) != "2012")]

# Now create a function to read in the Excel files, and capture the filename 
# as a variable. We will use this to create a month and year 

read.myfiles <- function(filename) {

  d <- read_xlsx(filename, sheet = "Raw Data") %>% 
  mutate(name = filename)
}

mydata <- lapply(file_names2, read.myfiles)
mydata2 <- bind_rows(mydata)

# Now examine the patterns for the filenames so that we can capture the dates 

table(mydata2$name)

# Some months have a 0 before the month, some do not. We have to do a little trick
# in the second mutate to make sure we capture the months correctly

mydata2 <- mydata2 %>% mutate(year = substr(name,3,6)) # All years are cols 3-6

mydata2 <- mutate(mydata2, month = ifelse( (substr(name,9,9) == "-"), substr(name,8,8),
                substr(name,8,9)))

table(mydata2$year)
table(mydata2$month)

# Now create a "legal" date 
mydata2$date <- as_date(paste(mydata2$year, mydata2$month, "01", sep="/"))
table(mydata2$date)

# Write a Stata output file for Paul to use
write.dta(mydata2, 
              "~/Google Drive/Research/AVR/data/monthly_regtotals_2013-2017_by_county_party.dta")

```
